### ISSUE TITLE
I want to add channel url directly to check every new livestreams

### ISSUE THREAD

**Issue by pessimistout** [limontec/Streamlink-Recorder#1]
how can we do this? is it possible? help me please.

**Comment by pessimistout** [comment]
i think i solved it. i added /live at the end of the channel link and it's worked.

**Comment by limontec** [comment]
You can check all commands lines here https://streamlink.github.io/cli.html to adapt on your code.
Add /live in url work only in the website you are testing. If you wanna record every time there are new livestream, just select the loop box.
