### ISSUE TITLE
how can i add custom plugin?

### ISSUE THREAD

**Issue by pessimistout** [limontec/Streamlink-Recorder#2]
hey. i want to add a plugin. how can i do this?

**Comment by limontec** [comment]
Descoment the line bellow in the code. Change the wget url to your custom plugin .py url and in the if put the name of the plugin after "{RUN_Dir}/".

`if not os.path.exists(f"{RUN_Dir}/.py"):
  !cd {RUN_Dir} && wget https://raw.githubusercontent.com/limontec/streamlink/master/src/streamlink/plugins/.py`

So if my plugin is named "test.py" it will look like:

`if not os.path.exists(f"{RUN_Dir}/test.py"):
  !cd {RUN_Dir} && wget https://mypluginongithub.com/test.py`

**Comment by pessimistout** [comment]
I was solved it. But this one works too.

How did i solved it: I put plugin file to streamlink folder. It was a bit hard to find folder but i finally found it :)

Thanks.

**Comment by limontec** [comment]
I see. But use the code, so you don't need to put the file in the folder manually every time you want to run.
